---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zachary.
--- DateTime: 3/8/2026 2:30 PM
---
--- ==================================
-- MATH & TRANSFORMS
--- ==================================

--TODO: figure out weather ? is needed or not
---@class Vector2
---@field x? number
---@field y? number
Vector2 = {}

---Returns the magnitude of the vector
---@return number
function Vector2:length() end

---Normalizes the vector in-place
---@return Vector2
function Vector2:normalize() end

---Constructor for new vector 2
---@param x number
---@param y number
---@return Vector2
function Vector2.new(x,y) end

---@class Vector3
---@field x number
---@field y number
---@field z number
Vector3 = {}
---Returns the magnitude of the vector
---@return number
function Vector3:length() end

---Normalizes the vector in-place
---@return Vector3
function Vector3:normalize() end

---Constructor for new vector 2
---@param x number
---@param y number
---@return Vector2
function Vector2.new(x,y) end
---@class Vector4
---@field x number
---@field y number
---@field z number
---@field w number
Vector4 = {}

---@class Rotation
---@field x number
---@field y number
---@field z number
Rotation = {}

---@class Scale
---@field x number
---@field y number
---@field z number
Scale = {}

---@class Transform
---@field position Vector3
---@field rotation Rotation
---@field scale Scale

---@return Transform
function Transform.new() end

--- ==================================
--- Random
--- ==================================
---@class random
random = {}

--- Later refoctor to auto detect for data type
--- Generates a random Integer between min and max
---@param min number
---@param max number
---@return number
function random.int(min, max) end

--- Generates a random Float between min and max
---@param min number
---@param max number
---@return number
function random.float(min, max) end

--- Generates a random Double between min and max
---@param min number
---@param max number
---@return number
function random.double(min, max) end

--- Generates a random bool between return true or false
---@return boolean
function random.bool() end

--- Generates a random Vector2 between min and max
---@param min number
---@param max number
---@return Vector2
function random.vector2(min, max) end

--- Generates a random Vector3 between min and max
---@param min number
---@param max number
---@return Vector3
function random.vector3(min, max) end

--- Generates a random Vector4 between min and max
---@param min number
---@param max number
---@return Vector4
function random.vector4(min, max) end

--- Generates a random unit Vector2 between min and max
---@return Vector2
function random.unit_vector2() end

--- Generates a random unit Vector3 between min and max
---@return Vector3
function random.unit_vector3() end

--- Generates a random unit Vector4 between min and max
---@return Vector4
function random.unit_vector4() end

--- Generates a random Color
---@return Color
function random.color() end


--- Generates a random float with a deviation from the base
---@param base number
---@param deviation number
---@return number
function random.deviation(base, deviation) end

--- ==================================
--- Math
--- ==================================
math = {}

--- Returns the sine of x; expects degrees
---@param x number
---@return number
function math.sin(x) end

--- Returns the cosine of x; expects degrees
---@param x number
---@return number
function math.cos(x) end

--- Returns the tangent of x; expects degrees
---@param x number
---@return number
function math.tan(x) end

--- Returns the arc sine of x; expects degrees
---@param x number
---@return number
function math.asin(x) end

--- Returns the arc cosine of x; expects degrees
---@param x number
---@return number
function math.acos(x) end

--- Returns the arc tangent of x; expects degrees
---@param x number
---@return number
function math.atan(x) end

--- Returns the arc tangent of y/x; expects degrees
---@param y number
---@param x number
---@return number
function math.atan2(y, x) end

--- Converts degrees to radians
---@param degrees number
---@return number
function math.to_radians(degrees) end

--- Converts radians to degrees
---@param radians number
---@return number
function math.to_degrees(radians) end

--- Clamps a value between a minimum and maximum range
---@param value number
---@param min number
---@param max number
---@return number
function math.clamp(value, min, max) end

--- Linearly interpolates between a and b by time t
---@param a number
---@param b number
---@param t number
---@return number
function math.lerp(a, b, t) end

--- Returns the square root of a value
---@param value number
---@return number
function math.sqrt(value) end

--- Returns the inverse square root (1 / sqrt(x))
---@param value number
---@return number
function math.inv_sqrt(value) end

--- Returns the absolute value
---@param value number
---@return number
function math.abs(value) end

--- Returns the floating-point remainder of x/y
---@param x number
---@param y number
---@return number
function math.fmod(x, y) end

--- Returns the largest integer less than or equal to x
---@param x number
---@return number
function math.floor(x) end

--- Returns the smallest integer greater than or equal to x
---@param x number
---@return number
function math.ceil(x) end

--- Returns the value rounded to the nearest integer
---@param x number
---@return number
function math.round(x) end

--- Returns the integer part of x (removes fractional part)
---@param x number
---@return number
function math.trunc(x) end

--- Returns the smaller of two values
---@param a number
---@param b number
---@return number
function math.min(a, b) end

--- Returns the larger of two values
---@param a number
---@param b number
---@return number
function math.max(a, b) end

--- Checks if two floats are nearly equal based on an epsilon
---@param a number
---@param b number
---@return boolean
function math.float_is_equal(a, b) end

--- ==================================
--- Graphics
--- ==================================
---@class Color
---@field r number
---@field g number
---@field b number
Color = {}

--- Creates a new Color object
---@overload fun(): Color
---@param r number
---@param g number
---@param b number
---@return Color
function Color.new(r, g, b) end

---@type Color
Color.white = { r = 1, g = 1, b = 1 }
---@type Color
Color.black = { r = 0, g = 0, b = 0 }

--- ==================================
--- Scene Management
--- ==================================
---@class Object
---@field color Color
---@field transform Transform
---@field texture Texture | nil
---@field is_filled boolean
Object = {}

--- Creates a new Objects, adds it to the scene, and returns a reference to it
---@return Object
function Object.new() end

---@class Scene
---@field objects Object[] -- Array-like table containing all objects in the scene
Scene = {}

--TODO: Auto add objects to scene, move from add objects to scene, rather focus on scene manip than control
--TODO: also i believe i broke this
function Scene.create_and_add() end

--- Creates a Sprite from a texture path, adds it to scene and returns reference
---@param path string
---@param transform Transform
---@return Sprite
function Scene:add_sprite(path, transform) end

--- ==================================
--- Input
--- ==================================

---@class Key
Key = {
    Unknown = 0,
    A = 1, B = 2, C = 3, D = 4, E = 5, F = 6, G = 7, H = 8, I = 9, J = 10,
    K = 11, L = 12, M = 13, N = 14, O = 15, P = 16, Q = 17, R = 18, S = 19, T = 20,
    U = 21, V = 22, W = 23, X = 24, Y = 25, Z = 26,
    D0 = 27, D1 = 28, D2 = 29, D3 = 30, D4 = 31, D5 = 32, D6 = 33, D7 = 34, D8 = 35, D9 = 36,
    Escape = 37, Enter = 38, Tab = 39, Backspace = 40, Insert = 41, Delete = 42,
    Right = 43, Left = 44, Up = 45, Down = 46,
    LeftShift = 47, LeftControl = 48, LeftAlt = 49, LeftSuper = 50,
    RightShift = 51, RightControl = 52, RightAlt = 53, RightSuper = 54,
    Space = 55
}

---@class keyboard
keyboard = {}

--- Returns true if the specified key is currently being pressed down
---@param key Key
---@return boolean
function Keyboard.is_down(key) end

--- ==================================
--- Audio
--- ==================================

---@class audio
audio = {}

--- Plays sound by path
---@param path string
function audio.play(path) end


--- ==================================
--- Rendering
--- ==================================

---@class Texture
Texture = {}

--- Creates a new Texture from an image file path
---@param path string
---@return Texture
function Texture.new(path) end

---@class Sprite : Object
---@field texture Texture
Sprite = {}

--- Creates a new Sprite using a texture and a color tint
---@param texture Texture
---@param color Color
---@return Sprite
function Sprite.new(texture, color) end